development:
  adapter: postgresql
  encoding: unicode
  database: adidas
  pool: 5
  username: adidas
  password: Abc@123456789
test:
  adapter: postgresql
  encoding: unicode
  database: adidas
  pool: 5
  username: adidas
  password: Abc@123456789
production:
  adapter: postgresql
  encoding: unicode
  database: aidas
  pool: 5
  username: adidas
  password: Abc@123456789
